# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Setup
name:         '@PigPen'
tagline:      'A messy Python 3.5 app for the pnut.io social network'
description:  'A messy Python 3.5 app for the pnut.io social network'

url:     https://bazbt3.github.io/PigPen/
baseurl: https://bazbt3.github.io/PigPen/

author:
  name:           '@bazbt3'

paginate:         5

# Use the following plug-ins:
gems:
  - jekyll-paginate # The official Jekyll paginator.
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem.

# Mess about with *this* line to force updates. This one! Yes!
